import { CloudinaryContext, Image, Video } from 'cloudinary-react'
import Head from 'next/head'
// import Image from 'next/image'
import { Avatar } from '../components/Avatar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Avatar 
          username='John Doe'
          profileImageUrl='https://i.pinimg.com/736x/38/93/07/389307d6af5c4be0051b7d3c4f93bf3d.jpg'
          size='large'
        />
          {/* <Image
            cloudName='wuphf'
            publicId='sample'
            width='200'
            height='200'
            crop='fill'
            gravity='face'
            effect='sepia'
          /> */}
        <CloudinaryContext cloudName='wuphf'>
          <div>
            <Video
              publicId='samples/elephants'
              width='200'
              height='200'
              crop='fill'
              gravity='face'
              effect='sepia'
            />
          </div>
        </CloudinaryContext>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <h1>Charles' Message</h1>
        <p>Woof meow</p>

        <h1>Sean's Message</h1>
        <p>Hello, my name is Sean. Practicing SourceTree with push and pull.</p>

        <h1>Zach's Message</h1>
        <p>Did I finally Get it?</p>

        <h1>Natalia's Message</h1>
        <p>Did this work??</p>

        <h1>Jeremiah's Message</h1>
        <p>Fork test</p>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
